CHROMIUM: glapi: Fix compilation when ./configure'd with --disable-asm
In file included from glapi_dispatch.c:90:0:
../../../src/mapi/glapi/glapitemp.h:1640:45: error: no previous prototype for 'glReadBufferNV' [-Wmissing-prototypes]
../../../src/mapi/glapi/glapitemp.h:4198:45: error: no previous prototype for 'glDrawBuffersNV' [-Wmissing-prototypes]
../../../src/mapi/glapi/glapitemp.h:6377:45: error: no previous prototype for 'glFlushMappedBufferRangeEXT' [-Wmissing-prototypes]
../../../src/mapi/glapi/glapitemp.h:6389:49: error: no previous prototype for 'glMapBufferRangeEXT' [-Wmissing-prototypes]
../../../src/mapi/glapi/glapitemp.h:6401:45: error: no previous prototype for 'glBindVertexArrayOES' [-Wmissing-prototypes]
../../../src/mapi/glapi/glapitemp.h:6413:45: error: no previous prototype for 'glDeleteVertexArraysOES' [-Wmissing-prototypes]
../../../src/mapi/glapi/glapitemp.h:6433:45: error: no previous prototype for 'glGenVertexArraysOES' [-Wmissing-prototypes]
../../../src/mapi/glapi/glapitemp.h:6445:50: error: no previous prototype for 'glIsVertexArrayOES' [-Wmissing-prototypes]

See also commits 8f3be339 (which fixed this once already), and 3ed8d42 (which
reverted the fix to fix it somewhere else [1])

[1] http://lists.freedesktop.org/archives/mesa-dev/2012-July/023899.html

BUG=none
TEST=compile

Signed-off-by: Jon TURNEY <jon.turney@dronecode.org.uk>
Signed-off-by: Prince Agyeman <prince.agyeman@intel.com>
Signed-off-by: Dhinakaran Pandiyan <dhinakaran.pandiyan@intel.com>
Signed-off-by: James Ausmus <james.ausmus@intel.com>
(applied manually from src/third_party/media-libs/mesa/files)

BUG=b:33533853
TEST=No CTS regressions on Cyan and Reef.

Signed-off-by: Tomasz Figa <tfiga@chromium.org>
Change-Id: Id71dc0f67acfbbe0bf4657b3339a2ed28b969d5a
Reviewed-on: https://chromium-review.googlesource.com/558123
Reviewed-by: Chad Versace <chadversary@chromium.org>

(cherry picked from branch cros/arc-17.2.0-pre1)
(cherry picked from commit e7cea6a16eb01e480447fd804d94f8f66daedc93)