util: include header files for expose 'close' function
Fixes: c72ff19a9ef ("vulkan/wsi: Close file descriptors in wsi_destroy_image")

error:
```
../../src/vulkan/wsi/wsi_common.c: In function 'wsi_destroy_image':
../../src/vulkan/wsi/wsi_common.c:515:7: error: implicit declaration of function 'close'; did you mean 'fclose'? [-Werror=implicit-function-declaration]
  515 |       close(image->dma_buf_fd);
      |       ^~~~~
      |       fclose
```

The `#if defined(_WIN32) && !defined(__CYGWIN__)` guard comes from c11/threads.h, but we should not expose threads.h in os_file.h

Signed-off-by: Yonggang Luo <luoyonggang@gmail.com>
Reviewed-by: Jesse Natalie <jenatali@microsoft.com>